### ISSUE TITLE
Stievie Premium

### ISSUE THREAD

**Issue by dremundorff** [wernerkarlheisenberg/plex-stieve#5] opened 2017-08-30 11:24 UTC
Thanks for the effort so far made. I've followed the exact procedure and under Channels either VRT NU or Stievie is not showing.
This is the stievie part in the general plex log: 

Aug 30, 2017 13:19:48.741 [0x700002248000] DEBUG - Starting plug-in /Users/dremundorff/Library/Application Support/Plex Media Server/Plug-ins/Stievie.bundle.
Aug 30, 2017 13:19:48.742 [0x700002248000] DEBUG - Starting file watcher for com.plexapp.plugins.stievie
Aug 30, 2017 13:19:48.744 [0x700002248000] DEBUG - Spawned plug-in com.plexapp.plugins.stievie with PID 68146
Aug 30, 2017 13:19:48.745 [0x700002248000] DEBUG - [com.plexapp.plugins.stievie] Sending command: GET /:/prefixes
Aug 30, 2017 13:19:49.672 [0x700001eb3000] DEBUG - Request: [127.0.0.1:61327 (Loopback)] GET /system/messaging/clear_events/com.plexapp.plugins.stievie (9 live) GZIP Signed-in Token (dremundorff)
Aug 30, 2017 13:19:49.672 [0x700001eb3000] DEBUG - [com.plexapp.system] Sending command over HTTP (GET): /system/messaging/clear_events/com.plexapp.plugins.stievie
Aug 30, 2017 13:19:49.672 [0x700001eb3000] DEBUG - HTTP requesting GET http://127.0.0.1:61289/system/messaging/clear_events/com.plexapp.plugins.stievie
Aug 30, 2017 13:19:49.721 [0x700001eb3000] DEBUG - HTTP 200 response from GET http://127.0.0.1:61289/system/messaging/clear_events/com.plexapp.plugins.stievie
Aug 30, 2017 13:19:49.721 [0x700001683000] DEBUG - Completed: [127.0.0.1:61327] 200 GET /system/messaging/clear_events/com.plexapp.plugins.stievie (9 live) GZIP 49ms 330 bytes

I've also attached the .bundles for both Stievie and VRT Nu and as well the 2 specific plugin logfiles in the archief.zip.

[Archief.zip](https://github.com/wernerkarlheisenberg/plex-stieve/files/1263351/Archief.zip)
[bundles.zip](https://github.com/wernerkarlheisenberg/plex-stieve/files/1263354/bundles.zip)

**Comment by dremundorff** [comment] 2017-08-30 11:43
By investigating the logfiles I've seen that the some files were missing. Added them all to the shared. I've got Stievie Premium as an account, can these channels be added? :-/

**Comment by wernerkarlheisenberg** [comment] 2017-08-31 10:40
Glad to hear it is working. Can you specify which additional items need to be copied to the Shared Folder? Can be useful for other users as well.

Regarding Stievie Premium, I will have a look. As you get the first month for free, I should be able to test it.

**Comment by dremundorff** [comment] 2017-08-31 10:55
Hereby the contents;

Certifi,chardet,idna,requests,urllib3

Thx for the efforts made!

Van: Bart Smeets <notifications@github.com>
Beantwoorden - Aan: wernerkarlheisenberg/plex-stieve <reply@reply.github.com>
Datum: donderdag 31 augustus 2017 om 12:40
Aan: wernerkarlheisenberg/plex-stieve <plex-stieve@noreply.github.com>
CC: Dre Mundorff <dre@mundorff.be>, Author <author@noreply.github.com>
Onderwerp: Re: [wernerkarlheisenberg/plex-stieve] Is this still working under Plex 1.8.1.4139 (#5)


Glad to hear it is working. Can you specify which additional items need to be copied to the Shared Folder? Can be useful for other users as well.

Regarding Stievie Premium, I will have a look. As you get the first month for free, I should be able to test it.

**Comment by wernerkarlheisenberg** [comment] 2017-09-01 14:38
The modules you mention are exactly the same as in this issue. Seems like the problem is not linked to Windows 8.1, but to the plex version. Can you confirm?

**Comment by wernerkarlheisenberg** [comment] 2017-09-01 14:40
I modified the topic of the issue to Stievie Premium and created a specific branch. Could you give it a try. Only file I changed until now is channels.pys.

**Comment by dremundorff** [comment] 2017-09-01 15:38
Yes I can confirm the same issue was occuring as on Windows 8.1. (Using Mac OS X)
Where do I find the updated channels.pys file?

**Comment by wernerkarlheisenberg** [comment] 2017-09-01 17:36
In order to help you forward, I included a [direct link](https://github.com/wernerkarlheisenberg/plex-stieve/blob/Stievie-Premium/Stievie.bundle/Contents/Services/Shared%20Code/channels.pys).

**Comment by dremundorff** [comment] 2017-09-02 09:48
Hi Bart,

It works! Thx! Now an epg integration and a way to ‘zap’ channels by swiping up/down?

Gr,

Dre
________________________________

**Comment by wernerkarlheisenberg** [comment] 2017-09-02 17:47
Changes are now part of the master branch. I added an option in preferences to specify whether you have a Stieve FREE of Stieve Premium account. Closing the issue.

**Closed by wernerkarlheisenberg** 2017-09-02 17:47 UTC
